// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-myyZ570zjhVXl_c6ow-iz9oXNCMOEUs',
    appId: '1:233183310004:web:f2052c07b6191edaac27e1',
    messagingSenderId: '233183310004',
    projectId: 'billey-64a3b',
    authDomain: 'billey-64a3b.firebaseapp.com',
    storageBucket: 'billey-64a3b.firebasestorage.app',
    measurementId: 'G-80ZC4008SF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx5N6TKbmgfkF7jDuKb9G0Mu8g21032zM',
    appId: '1:233183310004:android:f828324d5d9b3ac0ac27e1',
    messagingSenderId: '233183310004',
    projectId: 'billey-64a3b',
    storageBucket: 'billey-64a3b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE7z4Rw4wRl_RroFPkGpvRykN5sTk6pvY',
    appId: '1:233183310004:ios:51619a3ee8bd1f23ac27e1',
    messagingSenderId: '233183310004',
    projectId: 'billey-64a3b',
    storageBucket: 'billey-64a3b.firebasestorage.app',
    iosBundleId: 'com.billey.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAE7z4Rw4wRl_RroFPkGpvRykN5sTk6pvY',
    appId: '1:233183310004:ios:072e1fb9f8738f77ac27e1',
    messagingSenderId: '233183310004',
    projectId: 'billey-64a3b',
    storageBucket: 'billey-64a3b.firebasestorage.app',
    iosBundleId: 'com.billey.app',
  );
}
